set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_clock -period 10.000 -name clk100 -waveform {0.000 5.000} [get_ports clk100]
set_property PACKAGE_PIN E3 [get_ports {clk100}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk100}]

create_clock -period 40.000 -name clk -waveform {0.000 20.000} [get_ports clk]
set_property PACKAGE_PIN H16 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property PACKAGE_PIN H14 [get_ports {clk25}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk25}]

set_property PACKAGE_PIN C12 [get_ports {reset_l}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_l}]

set_property PACKAGE_PIN T10 [get_ports {ca}]
set_property PACKAGE_PIN R10 [get_ports {cb}]
set_property PACKAGE_PIN K16 [get_ports {cc}]
set_property PACKAGE_PIN K13 [get_ports {cd}]
set_property PACKAGE_PIN P15 [get_ports {ce}]
set_property PACKAGE_PIN T11 [get_ports {cf}]
set_property PACKAGE_PIN L18 [get_ports {cg}]
set_property PACKAGE_PIN H15 [get_ports {dp}]

set_property PACKAGE_PIN U13 [get_ports {an[7]}]
set_property PACKAGE_PIN K2  [get_ports {an[6]}]
set_property PACKAGE_PIN T14 [get_ports {an[5]}]
set_property PACKAGE_PIN P14 [get_ports {an[4]}]
set_property PACKAGE_PIN J14 [get_ports {an[3]}]
set_property PACKAGE_PIN T9  [get_ports {an[2]}]
set_property PACKAGE_PIN J18 [get_ports {an[1]}]
set_property PACKAGE_PIN J17 [get_ports {an[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ca}]
set_property IOSTANDARD LVCMOS33 [get_ports {cb}]
set_property IOSTANDARD LVCMOS33 [get_ports {cc}]
set_property IOSTANDARD LVCMOS33 [get_ports {cd}]
set_property IOSTANDARD LVCMOS33 [get_ports {ce}]
set_property IOSTANDARD LVCMOS33 [get_ports {cf}]
set_property IOSTANDARD LVCMOS33 [get_ports {cg}]
set_property IOSTANDARD LVCMOS33 [get_ports {dp}]

set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]